substitutions:
  name: apollo-msr-2-3f2654
  name_friendly: Hallway Presence Sensor

packages:
  ApolloAutomation.MSR-2: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2_BLE.yaml
  base_apollo: !include packages/base-apollo.yaml
