substitutions:
  name: apollo-msr-2-9896d0
  name_friendly: Spare Room Presence Sensor

packages:
  apolloautomation.msr-2: github://apolloautomation/msr-2/integrations/esphome/msr-2_ble.yaml
  base_apollo: !include packages/base-apollo.yaml
