substitutions:
  name: apollo-msr-2-9896d0
  name_friendly: Spare Room Presence Sensor

packages:
  apolloautomation.msr-2: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2_BLE.yaml@31e32d962da7ac16790df50f4fd7508217bdee72
  base_apollo: !include packages/base-apollo.yaml
