substitutions:
  name: bathroom-ducky
  name_friendly: Bathroom Ducky

api:
  encryption:
    key: !secret api_encryption_key

binary_sensor:
  - platform: ld2410
    has_moving_target:
      id: radar_has_moving_target
      name: Radar Moving Target
    has_still_target:
      id: radar_has_still_target
      name: Radar Still Target
    has_target:
      id: radar_has_target
      name: Radar Target
  - platform: status
    entity_category: diagnostic
    name: Online
  - platform: template
    device_class: occupancy
    icon: mdi:motion-sensor
    id: radar_zone_1_occupancy
    lambda: |-
      bool still_in_zone = id(radar_has_still_target).state && (id(radar_still_distance).state >= id(radar_z1_start).state) && (id(radar_still_distance).state <= id(radar_z1_end).state);
      bool moving_in_zone = id(radar_has_moving_target).state && (id(radar_moving_distance).state >= id(radar_z1_start).state) && (id(radar_moving_distance).state <= id(radar_z1_end).state);

      if (still_in_zone || moving_in_zone) {
        return true;
      } else {
        return false;
      }
    name: Radar Zone 1 Occupancy
  - platform: template
    device_class: occupancy
    icon: mdi:motion-sensor
    id: radar_zone_2_occupancy
    lambda: |-
      bool still_in_zone = id(radar_has_still_target).state && (id(radar_still_distance).state > id(radar_z1_end).state) && (id(radar_still_distance).state <= id(radar_z2_end).state);
      bool moving_in_zone = id(radar_has_moving_target).state && (id(radar_moving_distance).state > id(radar_z1_end).state) && (id(radar_moving_distance).state <= id(radar_z2_end).state);

      if (still_in_zone || moving_in_zone) {
        return true;
      } else {
        return false;
      }
    name: Radar Zone 2 Occupancy
  - platform: template
    device_class: occupancy
    icon: mdi:motion-sensor
    id: radar_zone_3_occupancy
    lambda: |-
      bool still_in_zone = id(radar_has_still_target).state && (id(radar_still_distance).state > id(radar_z2_end).state) && (id(radar_still_distance).state <= id(radar_z3_end).state);
      bool moving_in_zone = id(radar_has_moving_target).state && (id(radar_moving_distance).state > id(radar_z2_end).state) && (id(radar_moving_distance).state <= id(radar_z3_end).state);

      if (still_in_zone || moving_in_zone) {
        return true;
      } else {
        return false;
      }
    name: Radar Zone 3 Occupancy
  - platform: template
    device_class: occupancy
    icon: mdi:motion-sensor
    id: radar_zone_occupancy
    lambda: |-
      bool zone1 = id(radar_zone_1_occupancy).state;
      bool zone2 = id(radar_zone_2_occupancy).state;
      bool zone3 = id(radar_zone_3_occupancy).state;
      return zone1 || zone2 || zone3;
    name: Radar Zone Occupancy

button:
  - platform: ld2410
    factory_reset:
      name: Factory Reset Radar
    query_params:
      id: query_params_button
      name: Query Params
    restart:
      name: Restart Radar
  - platform: restart
    entity_category: diagnostic
    name: ESP Reboot

esp32:
  board: seeed_xiao_esp32c6
  variant: esp32c6
  framework:
    type: esp-idf

esphome:
  friendly_name: ${name_friendly}
  name: ${name}
  on_boot:
    - priority: -10
      then:
        - delay: 5s
        - button.press: query_params_button

ld2410:
  id: ld2410_radar

light:
  - platform: esp32_rmt_led_strip
    chipset: ws2812
    name: Night Light
    num_leds: 8
    pin: GPIO2
    restore_mode: RESTORE_DEFAULT_OFF
    rgb_order: GRB

logger:
  level: WARN

number:
  - platform: ld2410
    max_move_distance_gate:
      name: Radar Max Move Distance
    max_still_distance_gate:
      name: Radar Max Still Distance
    timeout:
      name: Radar Timeout
    g0:
      move_threshold:
        name: Radar G0 Move Threshold
      still_threshold:
        name: Radar G0 Still Threshold
    g1:
      move_threshold:
        name: Radar G1 Move Threshold
      still_threshold:
        name: Radar G1 Still Threshold
    g2:
      move_threshold:
        name: Radar G2 Move Threshold
      still_threshold:
        name: Radar G2 Still Threshold
    g3:
      move_threshold:
        name: Radar G3 Move Threshold
      still_threshold:
        name: Radar G3 Still Threshold
    g4:
      move_threshold:
        name: Radar G4 Move Threshold
      still_threshold:
        name: Radar G4 Still Threshold
    g5:
      move_threshold:
        name: Radar G5 Move Threshold
      still_threshold:
        name: Radar G5 Still Threshold
    g6:
      move_threshold:
        name: Radar G6 Move Threshold
      still_threshold:
        name: Radar G6 Still Threshold
    g7:
      move_threshold:
        name: Radar G7 Move Threshold
      still_threshold:
        name: Radar G7 Still Threshold
    g8:
      move_threshold:
        name: Radar G8 Move Threshold
      still_threshold:
        name: Radar G8 Still Threshold
  - platform: template
    device_class: distance
    entity_category: config
    icon: mdi:arrow-collapse-right
    id: radar_z1_start
    initial_value: 0
    max_value: 800
    min_value: 0
    mode: box
    name: Radar Zone 1 Start
    optimistic: true
    restore_value: true
    step: 1
    unit_of_measurement: cm
  - platform: template
    device_class: distance
    entity_category: config
    icon: mdi:arrow-collapse-right
    id: radar_z1_end
    initial_value: 50
    max_value: 800
    min_value: 0
    mode: box
    name: Radar End Zone 1
    optimistic: true
    restore_value: true
    step: 1
    unit_of_measurement: cm
  - platform: template
    device_class: distance
    entity_category: config
    icon: mdi:arrow-collapse-right
    id: radar_z2_end
    initial_value: 150
    max_value: 800
    min_value: 0
    mode: box
    name: Radar End Zone 2
    optimistic: true
    restore_value: true
    step: 1
    unit_of_measurement: cm
  - platform: template
    device_class: distance
    entity_category: config
    icon: mdi:arrow-collapse-right
    id: radar_z3_end
    initial_value: 250
    max_value: 800
    min_value: 0
    mode: box
    name: Radar End Zone 3
    optimistic: true
    restore_value: true
    step: 1
    unit_of_measurement: cm

ota:
  - platform: esphome
    password: !secret ota_password

safe_mode:

select:
  - platform: ld2410
    distance_resolution:
      name: Radar Gate Size

sensor:
  - platform: internal_temperature
    disabled_by_default: true
    entity_category: diagnostic
    filters:
      - lambda: |-
          static float last_reported_value = -6.0;
          float current_value = x;

          if (id(reduce_db_reporting).state) {
            if (abs(current_value - last_reported_value) >= 5.0) {
              last_reported_value = current_value;
              return current_value;
            } else {
              return {};
            }
          } else {
            last_reported_value = current_value;
            return current_value;
          }
    id: sys_esp_temperature
    name: ESP Temperature
  - platform: ld2410
    detection_distance:
      filters:
        - throttle_with_priority: 1000ms
        - lambda: |-
            if (!id(radar_has_target).state) return NAN;
            if (id(reduce_db_reporting).state) {
              static float last = 0;
              if (abs(x - last) < 5) return {};
              last = x;
            }
            return x;
      id: radar_detection_distance
      name: Radar Detection Distance
    g0:
      move_energy:
        name: Radar G0 Move Energy
      still_energy:
        name: Radar G0 Still Energy
    g1:
      move_energy:
        name: Radar G1 Move Energy
      still_energy:
        name: Radar G1 Still Energy
    g2:
      move_energy:
        name: Radar G2 Move Energy
      still_energy:
        name: Radar G2 Still Energy
    g3:
      move_energy:
        name: Radar G3 Move Energy
      still_energy:
        name: Radar G3 Still Energy
    g4:
      move_energy:
        name: Radar G4 Move Energy
      still_energy:
        name: Radar G4 Still Energy
    g5:
      move_energy:
        name: Radar G5 Move Energy
      still_energy:
        name: Radar G5 Still Energy
    g6:
      move_energy:
        name: Radar G6 Move Energy
      still_energy:
        name: Radar G6 Still Energy
    g7:
      move_energy:
        name: Radar G7 Move Energy
      still_energy:
        name: Radar G7 Still Energy
    g8:
      move_energy:
        name: Radar G8 Move Energy
      still_energy:
        name: Radar G8 Still Energy
    moving_distance:
      filters:
        - throttle_with_priority: 1000ms
        - lambda: |-
            if (!id(radar_has_moving_target).state) return NAN;
            if (id(reduce_db_reporting).state) {
              static float last = 0;
              if (abs(x - last) < 5) return {};
              last = x;
            }
            return x;
      id: radar_moving_distance
      name: Radar Moving Distance
    moving_energy:
      filters:
        - throttle_with_priority: 1000ms
        - lambda: |-
            if (id(reduce_db_reporting).state) return {};
            return x;
      id: radar_moving_energy
      name: Radar Move Energy
    still_distance:
      filters:
        - throttle_with_priority: 1000ms
        - lambda: |-
            if (!id(radar_has_still_target).state) return NAN;
            if (id(reduce_db_reporting).state) {
              static float last = 0;
              if (abs(x - last) < 5) return {};
              last = x;
            }
            return x;
      id: radar_still_distance
      name: Radar Still Distance
    still_energy:
      filters:
        - throttle_with_priority: 1000ms
        - lambda: |-
            if (id(reduce_db_reporting).state) return {};
            return x;
      id: radar_still_energy
      name: Radar Still Energy
  - platform: uptime
    disabled_by_default: true
    entity_category: diagnostic
    id: sys_uptime
    name: Uptime
    update_interval: 60s
  - platform: wifi_signal
    disabled_by_default: true
    entity_category: diagnostic
    id: wifi_signal_db
    name: WiFi Signal
    update_interval: 60s

switch:
  - platform: ld2410
    bluetooth:
      id: radar_bluetooth
      name: LD2410 Bluetooth
      restore_mode: RESTORE_DEFAULT_OFF
    engineering_mode:
      name: Radar Engineering Mode
  - platform: template
    entity_category: config
    icon: mdi:database
    id: reduce_db_reporting
    name: Reduce DB Reporting
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

text_sensor:
  - platform: ld2410
    mac_address:
      entity_category: diagnostic
      name: Radar Bluetooth MAC
    version:
      entity_category: diagnostic
      name: Radar Firmware Version
  - platform: version
    entity_category: diagnostic
    hide_timestamp: true
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      entity_category: diagnostic
      name: IP Address
    mac_address:
      entity_category: diagnostic
      name: MAC Address

uart:
  baud_rate: 256000
  rx_pin: GPIO23
  tx_pin: GPIO16

web_server:
  port: 80
  version: 3

wifi:
  password: !secret wifi_password
  ssid: !secret wifi_ssid
