substitutions:
  name: bedroom-fan
  name_friendly: Bedroom Fan

packages:
  base: !include packages/base.yaml
  diagnostics: !include packages/basic-diagnostics.yaml
  web_server: !include packages/web-server.yaml
  fan: !include packages/vornado-fan.yaml
