substitutions:
  name: hallway-front-door-keypad
  name_friendly: Hallway Front Door Keypad

packages:
  base: !include packages/base.yaml
  diagnostics: !include packages/diagnostics.yaml

esp32:
  board: m5stack-atom

external_components:
  - components: [switchbot_keypad_bridge]
    source: github://pierluigizagaria/switchbot-keypad-bridge@51d5049080232f4a2b7fa843a9411e57af88416b

light:
  - platform: esp32_rmt_led_strip
    channel_colors: GRB
    chipset: sk6812
    internal: true
    name: Status LED
    num_leds: 1
    pin: GPIO27

switchbot_keypad_bridge:
  keypad:
    name: Keypad
  keypad_action:
    name: Action
  keypad_battery_level:
    name: Keypad Battery
  on_unlock:
    - homeassistant.event:
        event: esphome.switchbot_keypad_unlock
        data:
          index: !lambda 'return to_string(index);'
          method: !lambda 'return method;'
  reset_button:
    name: Reset

time:
  - platform: sntp
