substitutions:
  name: hallway-front-door-keypad
  name_friendly: Hallway Front Door Keypad

packages:
  base: !include packages/base.yaml

button:
  - platform: restart
    entity_category: diagnostic
    name: ESP Reboot

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

external_components:
  - source: github://pierluigizagaria/switchbot-keypad-bridge
    components: [switchbot_keypad_bridge]

light:
  - platform: esp32_rmt_led_strip
    chipset: sk6812
    internal: true
    name: Status LED
    num_leds: 1
    pin: GPIO27
    rgb_order: GRB

sensor:
  - platform: internal_temperature
    disabled_by_default: true
    entity_category: diagnostic
    name: ESP Temperature
  - platform: uptime
    disabled_by_default: true
    entity_category: diagnostic
    name: Uptime
    update_interval: 60s
  - platform: wifi_signal
    disabled_by_default: true
    entity_category: diagnostic
    name: WiFi Signal
    update_interval: 60s

switchbot_keypad_bridge:
  battery_level:
    name: Keypad Battery
  keypad:
    name: Keypad
  keypad_action:
    name: Action
  on_unlock:
    - homeassistant.event:
        event: esphome.switchbot_keypad_unlock
        data:
          index: !lambda 'return to_string(index);'
          method: !lambda 'return method;'
  unpair_button:
    name: Unpair

text_sensor:
  - platform: version
    entity_category: diagnostic
    hide_timestamp: true
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      entity_category: diagnostic
      name: IP Address
    mac_address:
      entity_category: diagnostic
      name: MAC Address

time:
  - platform: sntp
