substitutions:
  name: hallway-front-door-keypad
  name_friendly: Hallway Front Door Keypad

packages:
  base: !include packages/base.yaml
  diagnostics: !include packages/diagnostics.yaml

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

external_components:
  - components: [switchbot_keypad_bridge]
    source: github://pierluigizagaria/switchbot-keypad-bridge

light:
  - platform: esp32_rmt_led_strip
    chipset: sk6812
    internal: true
    name: Status LED
    num_leds: 1
    pin: GPIO27
    rgb_order: GRB

switchbot_keypad_bridge:
  battery_level:
    name: Keypad Battery
  keypad:
    name: Keypad
  keypad_action:
    name: Action
  on_unlock:
    - homeassistant.event:
        event: esphome.switchbot_keypad_unlock
        data:
          index: !lambda 'return to_string(index);'
          method: !lambda 'return method;'
  unpair_button:
    name: Unpair

time:
  - platform: sntp
