substitutions:
  name: kitchen-presence-sensor
  name_friendly: Kitchen Presence Sensor

packages:
  base: !include packages/base.yaml
  diagnostics: !include packages/diagnostics.yaml
  web_server: !include packages/web-server.yaml

binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: Radar Target

esp32:
  board: seeed_xiao_esp32c6

i2c:
  scl: GPIO23
  sda: GPIO22

light:
  - platform: esp32_rmt_led_strip
    channel_colors: GRB
    chipset: ws2812
    internal: true
    name: Status LED
    num_leds: 1
    pin: GPIO1

seeed_mr60bha2:

sensor:
  - platform: bh1750
    name: Illuminance
  - platform: seeed_mr60bha2
    breath_rate:
      name: Respiratory Rate
      unit_of_measurement: breaths/min
    distance:
      name: Distance
    heart_rate:
      name: Heart Rate
    num_targets:
      name: Target Count

uart:
  baud_rate: 115200
  rx_pin: GPIO17
  tx_pin: GPIO16
