esphome:
  name: living-room-ducky
  friendly_name: Living Room Ducky

# Replace this with your actual platform if you aren't using ESP32.
esp32:
  board: esp32dev

logger:

api:
  encryption:
    key: "BNvf/Q/MWC4N1TqaqyekJuYL0g9zVfA5L9+TPw4dMeo="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Living Room Duc Fallback Hotspot
    password: "jW753BDpAou3"

captive_portal:
