substitutions:
  light_name: Lamp
  light_num_leds: 16
  name: living-room-ducky
  name_friendly: Living Room Ducky

packages:
  base: !include packages/base.yaml
  ducky: !include packages/ducky.yaml
  web_server: !include packages/web-server.yaml
