substitutions:
  config_ir_address: 0xFF00
  config_ir_mute_command: 0xBB44
  config_ir_volume_down_command: 0xE916
  config_ir_volume_up_command: 0xE619
  entity_speakers: media_player.living_room_speakers
  name: living-room-speakers-remote
  name_friendly: Living Room Speakers Remote

packages:
  speakers_remote: !include packages/speakers-remote.yaml
