substitutions:
  config_ir_address: 0xFF00
  config_ir_mute_command: 0xBB44
  config_ir_volume_down_command: 0xE916
  config_ir_volume_up_command: 0xE619
  entity_speakers: media_player.living_room_speakers
  name: living-room-speakers-remote
  name_friendly: Living Room Speakers Remote

api:
  encryption:
    key: !secret api_encryption_key

binary_sensor:
  - platform: gpio
    filters:
      - delayed_on: 10ms
    name: Button
    on_press:
      - script.execute: flash_red
      - script.execute: toggle_mute
    pin:
      inverted: true
      number: GPIO39
  - platform: homeassistant
    attribute: is_volume_muted
    entity_id: ${entity_speakers}
    id: current_mute_state
  - platform: remote_receiver
    internal: true
    name: IR Mute
    nec:
      address: ${config_ir_address}
      command: ${config_ir_mute_command}
    on_press:
      - script.execute: flash_red
      - script.execute: toggle_mute
  - platform: remote_receiver
    internal: true
    name: IR Volume Down
    nec:
      address: ${config_ir_address}
      command: ${config_ir_volume_down_command}
    on_press:
      - script.execute: flash_red
      - script.execute: volume_down
  - platform: remote_receiver
    internal: true
    name: IR Volume Up
    nec:
      address: ${config_ir_address}
      command: ${config_ir_volume_up_command}
    on_press:
      - script.execute: flash_red
      - script.execute: volume_up
  - platform: status
    entity_category: diagnostic
    name: Online

button:
  - platform: restart
    entity_category: diagnostic
    name: ESP Reboot
  - platform: template
    name: Mute
    on_press:
      - script.execute: flash_red
      - script.execute: toggle_mute
  - platform: template
    name: Volume Down
    on_press:
      - script.execute: flash_red
      - script.execute: volume_down
  - platform: template
    name: Volume Up
    on_press:
      - script.execute: flash_red
      - script.execute: volume_up

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

esphome:
  friendly_name: ${name_friendly}
  name: ${name}

light:
  - platform: esp32_rmt_led_strip
    chipset: sk6812
    id: status_led
    internal: true
    name: Status LED
    num_leds: 1
    pin: GPIO27
    rgb_order: GRB

logger:
  level: WARN

ota:
  - platform: esphome
    password: !secret ota_password

safe_mode:

remote_receiver:
  pin:
    inverted: true
    mode: INPUT_PULLUP
    number: GPIO32

script:
  - id: flash_red
    then:
      - light.turn_on:
          blue: 0%
          flash_length: 100ms
          green: 0%
          id: status_led
          red: 100%
  - id: toggle_mute
    then:
      - homeassistant.action:
          action: media_player.volume_mute
          data:
            entity_id: ${entity_speakers}
            is_volume_muted: !lambda return !id(current_mute_state).state;
  - id: volume_down
    then:
      - homeassistant.action:
          action: media_player.volume_down
          data:
            entity_id: ${entity_speakers}
  - id: volume_up
    then:
      - homeassistant.action:
          action: media_player.volume_up
          data:
            entity_id: ${entity_speakers}

sensor:
  - platform: internal_temperature
    disabled_by_default: true
    entity_category: diagnostic
    name: ESP Temperature
  - platform: uptime
    disabled_by_default: true
    entity_category: diagnostic
    name: Uptime
    update_interval: 60s
  - platform: wifi_signal
    disabled_by_default: true
    entity_category: diagnostic
    name: WiFi Signal
    update_interval: 60s

text_sensor:
  - platform: version
    entity_category: diagnostic
    hide_timestamp: true
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      entity_category: diagnostic
      name: IP Address
    mac_address:
      entity_category: diagnostic
      name: MAC Address

web_server:
  port: 80
  version: 3

wifi:
  password: !secret wifi_password
  ssid: !secret wifi_ssid
