substitutions:
  name: spare-bathroom-ducky
  name_friendly: Spare Bathroom Ducky

packages:
  base: !include packages/base.yaml
  diagnostics: !include packages/diagnostics.yaml
  web_server: !include packages/web-server.yaml

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf
  variant: esp32c6

light:
  - platform: esp32_rmt_led_strip
    chipset: ws2812
    name: Night Light
    num_leds: 8
    pin: GPIO2
    rgb_order: GRB

sensor:
  - id: !extend sys_esp_temperature
    filters:
      - lambda: |-
          static float last_reported_value = -6.0;
          float current_value = x;

          if (id(reduce_db_reporting).state) {
            if (abs(current_value - last_reported_value) >= 5.0) {
              last_reported_value = current_value;
              return current_value;
            } else {
              return {};
            }
          } else {
            last_reported_value = current_value;
            return current_value;
          }

switch:
  - platform: template
    entity_category: config
    icon: mdi:database
    id: reduce_db_reporting
    name: Reduce DB Reporting
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
