binary_sensor:
  - platform: status
    entity_category: diagnostic
    name: Online

button:
  - platform: restart
    entity_category: diagnostic
    name: ESP Reboot

sensor:
  - platform: internal_temperature
    disabled_by_default: true
    entity_category: diagnostic
    id: sys_esp_temperature
    name: ESP Temperature
    filters:
      - lambda: |-
          static float last = NAN;
          if (isnan(last) || abs(x - last) >= 5.0f) {
            last = x;
            return x;
          }
          return {};
  - platform: uptime
    disabled_by_default: true
    entity_category: diagnostic
    id: sys_uptime
    name: Uptime
  - platform: wifi_signal
    disabled_by_default: true
    entity_category: diagnostic
    id: wifi_signal_db
    name: WiFi Signal

text_sensor:
  - platform: version
    entity_category: diagnostic
    hide_timestamp: true
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      entity_category: diagnostic
      name: IP Address
    mac_address:
      entity_category: diagnostic
      name: MAC Address
